language: node_js
sudo: false
git:
  depth: 1
cache:
  directories:
    - $HOME/.npm
    - node_modules
matrix:
  include:
    - node_js: "11"
      script: npm run jest -- --runInBand
      env: CI=tests 11
    - node_js: "10"
      script: npm run jest -- --runInBand
      env: CI=tests 10
    - node_js: "8"
      script: npm run pretest
      env: CI=pretest
    - node_js: "8"
      script: npm run jest -- --runInBand  --coverage
      env: CI=coverage

before_install:
  - npm install -g npm@latest
